# Generated by Django 5.2.4 on 2025-08-21 22:53

import django.core.validators
import django.db.models.deletion
import meetings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_resume', models.TextField()),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('ar', 'العربية')], default='fr', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=meetings.models._rapport_upload_to)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='meetings.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date_r', models.DateField()),
                ('heure_r', models.TimeField()),
                ('status', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé'), ('reporte', 'Reporté')], default='planifie', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='reunions_participees', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunions_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_r', '-heure_r', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemin_fichier', models.FileField(upload_to=meetings.models._audio_upload_to)),
                ('format', models.CharField(blank=True, max_length=15)),
                ('duree', models.PositiveIntegerField(blank=True, help_text='Durée en secondes', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='meetings.reunion')),
            ],
            options={
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_transcrit', models.TextField()),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('ar', 'العربية')], default='fr', max_length=5)),
                ('heure_date', models.DateTimeField(auto_now_add=True)),
                ('reunion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='meetings.reunion')),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='transcription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='meetings.transcription'),
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('start_sec', models.FloatField(default=0)),
                ('end_sec', models.FloatField(default=0)),
                ('speaker', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='meetings.reunion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='reunion',
            index=models.Index(fields=['utilisateur', 'date_r', 'heure_r'], name='meetings_re_utilisa_e05ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='reunion',
            index=models.Index(fields=['status'], name='meetings_re_status_ca35bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='reunion',
            constraint=models.UniqueConstraint(fields=('utilisateur', 'date_r', 'heure_r', 'titre'), name='uniq_reunion_owner_datetime_title'),
        ),
        migrations.AddIndex(
            model_name='audio',
            index=models.Index(fields=['reunion'], name='meetings_au_reunion_5fe736_idx'),
        ),
        migrations.AddIndex(
            model_name='transcription',
            index=models.Index(fields=['reunion'], name='meetings_tr_reunion_7f2780_idx'),
        ),
        migrations.AddIndex(
            model_name='transcription',
            index=models.Index(fields=['langue'], name='meetings_tr_langue_6ef576_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['transcription'], name='meetings_re_transcr_c573e8_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['date_generation'], name='meetings_re_date_ge_1586e4_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptsegment',
            index=models.Index(fields=['reunion'], name='meetings_tr_reunion_e8ec60_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptsegment',
            index=models.Index(fields=['created_at'], name='meetings_tr_created_1327cd_idx'),
        ),
    ]
